# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64   
     goamd64:
      - v3
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
sboms:
  - artifacts: archive
report_sizes: true
release:
  github:
    owner: mlnoga
    name: go-imap-backup
