before:
  hooks:
    - go mod tidy
    # - go generate ./...
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      - v2
      - v3
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}
    
archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
checksum:
  name_template: 'checksums.txt'
sboms:
  - artifacts: archive
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
report_sizes: true
