before:
  hooks:
    - go mod tidy
    # - go generate ./...
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64   
    amd64:
      - v2
      - v3
archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
sboms:
  - artifacts: archive
report_sizes: true
release:
  github:
    owner: mlnoga
    name: go-imap-backup
